package tqs.airquality.selenium;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class GetCacheDetailsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void getCacheDetails() {
    driver.get("http://localhost:3000/aqi/dashboard");
    driver.manage().window().setSize(new Dimension(1360, 684));
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiList-root:nth-child(1) > .makeStyles-item-15:nth-child(4) .MuiListItemText-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiList-root:nth-child(1) > .makeStyles-item-15:nth-child(4) .MuiListItemText-root")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".makeStyles-success-287"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".makeStyles-success-287")).click();
    driver.findElement(By.cssSelector(".makeStyles-cardBody-401 > h3")).click();
    driver.findElement(By.cssSelector(".makeStyles-cardBody-401 > h3")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".makeStyles-cardBody-401 > h3"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("h3 > strong:nth-child(1)")).click();
    driver.findElement(By.cssSelector("h3 > strong:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h3 > strong:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("h4:nth-child(2) > strong:nth-child(1)")).click();
    driver.findElement(By.cssSelector("h4:nth-child(2) > strong:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h4:nth-child(2) > strong:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("h4:nth-child(2) > strong:nth-child(3)")).click();
    driver.findElement(By.cssSelector("h4:nth-child(2) > strong:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h4:nth-child(2) > strong:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("h4:nth-child(3) > strong:nth-child(1)")).click();
    driver.findElement(By.cssSelector("h4:nth-child(3) > strong:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h4:nth-child(3) > strong:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("h4:nth-child(3) > strong:nth-child(3)")).click();
    driver.findElement(By.cssSelector("h4:nth-child(3) > strong:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h4:nth-child(3) > strong:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("div > strong")).click();
    driver.findElement(By.cssSelector("div > strong")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div > strong"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
  }
}
