package tqs.airQuality.selenium;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GetLisbonAirQualityTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void getLisbonAirQuality() {
    driver.get("http://localhost:3000/aqi/dashboard");
    driver.manage().window().setSize(new Dimension(1360, 684));
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiList-root:nth-child(1) > .makeStyles-item-15:nth-child(3) .MuiListItemText-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiList-root:nth-child(1) > .makeStyles-item-15:nth-child(3) .MuiListItemText-root")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("outlined-adornment-amount")).click();
    driver.findElement(By.id("outlined-adornment-amount")).sendKeys("lisbon");
    driver.findElement(By.cssSelector(".makeStyles-success-287")).click();
    driver.findElement(By.cssSelector("h3:nth-child(2)")).click();
    driver.findElement(By.cssSelector("h3:nth-child(2)")).click();
    driver.findElement(By.cssSelector("h3:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h3:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("h4")).click();
    driver.findElement(By.cssSelector(".makeStyles-cardBodyProfile-424")).click();
    driver.findElement(By.cssSelector(".makeStyles-cardBodyProfile-424")).click();
    driver.findElement(By.cssSelector("span:nth-child(9) > strong")).click();
    driver.findElement(By.cssSelector("span:nth-child(9) > strong")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("span:nth-child(9) > strong"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("span:nth-child(9)")).click();
    driver.findElement(By.cssSelector("span:nth-child(9)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("span:nth-child(9)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
  }
}
