package tqs.airquality.selenium;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class GetProjectDetailsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void getProjectDetails() {
    driver.get("http://localhost:3000/aqi/dashboard");
    driver.manage().window().setSize(new Dimension(1360, 684));
    driver.findElement(By.cssSelector(".MuiList-root:nth-child(1) > .makeStyles-item-15:nth-child(5) .MuiListItemText-root")).click();
    driver.findElement(By.cssSelector("strong:nth-child(2)")).click();
    driver.findElement(By.cssSelector("strong:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("strong:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("li:nth-child(1)")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) > strong")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(1) > strong"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("li:nth-child(1) > strong")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) > strong")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) > strong")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(2) > strong"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("li:nth-child(3) > strong")).click();
    driver.findElement(By.cssSelector("li:nth-child(3) > strong")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(3) > strong"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("h4 > strong")).click();
    driver.findElement(By.cssSelector("h4 > strong")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h4 > strong"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("em")).click();
    driver.findElement(By.cssSelector("em")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("em"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
  }
}
